#services:
#    # PHP-FPM
#    app:
#        build: ./docker/php
#        restart: unless-stopped
#        volumes:
#            - ./app:/app
#        networks:
#            app-network:
#                aliases:
#                    - php-fpm-app
#        depends_on:
#            - mariadb
#            - redis
#
#    # Nginx
#    nginx:
#        image: nginx:latest
#        restart: unless-stopped
#        volumes:
#            - ./app:/app
#            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
#        networks:
#            - app-network
#        ports:
#            - "8099:80"
#        depends_on:
#            - app
#
#    # MariaDB
#    mariadb:
#        image: mariadb:latest
#        restart: unless-stopped
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: my_app
#        volumes:
#            - mariadb-data:/var/lib/mysql
#        networks:
#            - app-network
#        ports:
#            - "3302:3306"
#
#    # Redis
#    redis:
#        image: redis:alpine
#        restart: unless-stopped
#        networks:
#            - app-network
#        ports:
#            - "6380:6379"
#
#    # Mailhog
##    mailhog:
##        platform: linux/x86_64
##        image: mailhog/mailhog
##        restart: unless-stopped
##        networks:
##            - app-network
##        ports:
##            - 1029:1027
##            - 8029:8027
#
## Volumes
#volumes:
#    mariadb-data:
#
## Networks
#networks:
#    app-network:
#        driver: bridge
# docker-compose.yml mejorado
services:
    app:
        build: ./docker/php
        restart: unless-stopped
        volumes:
            - ./app:/app
        networks:
            app-network:
                aliases:
                    - php-fpm-app
        depends_on:
            - mariadb
            - redis
        environment:
            COMPOSER_ALLOW_SUPERUSER: 1

    nginx:
        image: nginx:latest
        restart: unless-stopped
        volumes:
            - ./app:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network
        ports:
            - "8099:80"
        depends_on:
            - app

    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
            MYSQL_DATABASE: ${MYSQL_DATABASE:-my_app}
        volumes:
            - mariadb-data:/var/lib/mysql
        networks:
            - app-network
        ports:
            - "3302:3306"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:alpine
        restart: unless-stopped
        networks:
            - app-network
        ports:
            - "6380:6379"
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

#    mailhog:
#        platform: linux/x86_64
#        image: mailhog/mailhog
#        restart: unless-stopped
#        networks:
#            - app-network
#        ports:
#            - 1029:1027
#            - 8029:8027

volumes:
    mariadb-data:

networks:
    app-network:
        driver: bridge
